apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker
resources:
  - ../../base
  - ingress.yaml
  - namespace.yaml
images:
  - name: ghcr.io/krishnamadhavan/expense-tracker
    newTag: local
