{{- if .Values.migrate.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expense-tracker.fullname" . }}-migrations
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/migrations/*" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
